/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAbandonedCartRouteImport } from './routes/_app.abandoned-cart'
import { Route as AppActivityLogsRouteImport } from './routes/_app.activity-logs'
import { Route as AppAffiliatesRouteImport } from './routes/_app.affiliates'
import { Route as AppAgentDeliveriesRouteImport } from './routes/_app.agent-deliveries'
import { Route as AppAgentPerformanceRouteImport } from './routes/_app.agent-performance'
import { Route as AppAgentStockRouteImport } from './routes/_app.agent-stock'
import { Route as AppAgentsRouteImport } from './routes/_app.agents'
import { Route as AppAiRouteImport } from './routes/_app.ai'
import { Route as AppApiTestCenterRouteImport } from './routes/_app.api-test-center'
import { Route as AppAssignmentRulesRouteImport } from './routes/_app.assignment-rules'
import { Route as AppBroadcastHistoryRouteImport } from './routes/_app.broadcast-history'
import { Route as AppBuyStockRouteImport } from './routes/_app.buy-stock'
import { Route as AppCallLogsRouteImport } from './routes/_app.call-logs'
import { Route as AppCallQueueRouteImport } from './routes/_app.call-queue'
import { Route as AppCampaignAttributionRouteImport } from './routes/_app.campaign-attribution'
import { Route as AppCampaignsRouteImport } from './routes/_app.campaigns'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppCheckoutRouteImport } from './routes/_app.checkout'
import { Route as AppComplaintsRouteImport } from './routes/_app.complaints'
import { Route as AppCustomerNotesRouteImport } from './routes/_app.customer-notes'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppDangerZoneRouteImport } from './routes/_app.danger-zone'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppDeliveryRouteImport } from './routes/_app.delivery'
import { Route as AppEmailMarketingRouteImport } from './routes/_app.email-marketing'
import { Route as AppEmbedFormsRouteImport } from './routes/_app.embed-forms'
import { Route as AppFaultyStockRouteImport } from './routes/_app.faulty-stock'
import { Route as AppFinanceRouteImport } from './routes/_app.finance'
import { Route as AppFinanceLedgerRouteImport } from './routes/_app.finance-ledger'
import { Route as AppFollowUpsRouteImport } from './routes/_app.follow-ups'
import { Route as AppFormSubmissionsRouteImport } from './routes/_app.form-submissions'
import { Route as AppFormsRouteImport } from './routes/_app.forms'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppMessageTemplatesRouteImport } from './routes/_app.message-templates'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppOrdersRouteImport } from './routes/_app.orders'
import { Route as AppProductAnalyticsRouteImport } from './routes/_app.product-analytics'
import { Route as AppProductsRouteImport } from './routes/_app.products'
import { Route as AppProfitDashboardRouteImport } from './routes/_app.profit-dashboard'
import { Route as AppPromoterTargetsRouteImport } from './routes/_app.promoter-targets'
import { Route as AppPromotersRouteImport } from './routes/_app.promoters'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppReturnsRouteImport } from './routes/_app.returns'
import { Route as AppRolesPermissionsRouteImport } from './routes/_app.roles-permissions'
import { Route as AppSalesCohortsRouteImport } from './routes/_app.sales-cohorts'
import { Route as AppSalesManagerOfficeRouteImport } from './routes/_app.sales-manager-office'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSmsAutomationRouteImport } from './routes/_app.sms-automation'
import { Route as AppStaffRouteImport } from './routes/_app.staff'
import { Route as AppStaffEarningsRouteImport } from './routes/_app.staff-earnings'
import { Route as AppStaffPerformanceRouteImport } from './routes/_app.staff-performance'
import { Route as AppStateWhatsappGroupsRouteImport } from './routes/_app.state-whatsapp-groups'
import { Route as AppStockRecordRouteImport } from './routes/_app.stock-record'
import { Route as AppStorefrontRouteImport } from './routes/_app.storefront'
import { Route as AppStorefrontCustomizationRouteImport } from './routes/_app.storefront-customization'
import { Route as AppTrackingRouteImport } from './routes/_app.tracking'
import { Route as AppWalletRouteImport } from './routes/_app.wallet'
import { Route as AppWaybillRouteImport } from './routes/_app.waybill'
import { Route as AppWhatsappAutomationRouteImport } from './routes/_app.whatsapp-automation'
import { Route as FormSlugRouteImport } from './routes/form.$slug'
import { Route as SystemCreateOwnerRouteImport } from './routes/system.create-owner'
import { Route as TrackOrderCodeRouteImport } from './routes/track.$orderCode'
import { Route as AppConnectionsAiProviderRouteImport } from './routes/_app.connections.ai-provider'
import { Route as AppConnectionsElementorRouteImport } from './routes/_app.connections.elementor'
import { Route as AppConnectionsEmailRouteImport } from './routes/_app.connections.email'
import { Route as AppConnectionsPaymentGatewaysRouteImport } from './routes/_app.connections.payment-gateways'
import { Route as AppConnectionsSmsRouteImport } from './routes/_app.connections.sms'
import { Route as AppConnectionsWebhooksRouteImport } from './routes/_app.connections.webhooks'
import { Route as AppConnectionsWhatsappRouteImport } from './routes/_app.connections.whatsapp'
import { Route as AppConnectionsWoocommerceRouteImport } from './routes/_app.connections.woocommerce'
import { Route as AppOrdersIdRouteImport } from './routes/_app.orders.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAbandonedCartRoute = AppAbandonedCartRouteImport.update({
  id: '/abandoned-cart',
  path: '/abandoned-cart',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityLogsRoute = AppActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppAffiliatesRoute = AppAffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentDeliveriesRoute = AppAgentDeliveriesRouteImport.update({
  id: '/agent-deliveries',
  path: '/agent-deliveries',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentPerformanceRoute = AppAgentPerformanceRouteImport.update({
  id: '/agent-performance',
  path: '/agent-performance',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentStockRoute = AppAgentStockRouteImport.update({
  id: '/agent-stock',
  path: '/agent-stock',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppApiTestCenterRoute = AppApiTestCenterRouteImport.update({
  id: '/api-test-center',
  path: '/api-test-center',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentRulesRoute = AppAssignmentRulesRouteImport.update({
  id: '/assignment-rules',
  path: '/assignment-rules',
  getParentRoute: () => AppRoute,
} as any)
const AppBroadcastHistoryRoute = AppBroadcastHistoryRouteImport.update({
  id: '/broadcast-history',
  path: '/broadcast-history',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyStockRoute = AppBuyStockRouteImport.update({
  id: '/buy-stock',
  path: '/buy-stock',
  getParentRoute: () => AppRoute,
} as any)
const AppCallLogsRoute = AppCallLogsRouteImport.update({
  id: '/call-logs',
  path: '/call-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppCallQueueRoute = AppCallQueueRouteImport.update({
  id: '/call-queue',
  path: '/call-queue',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignAttributionRoute = AppCampaignAttributionRouteImport.update({
  id: '/campaign-attribution',
  path: '/campaign-attribution',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppComplaintsRoute = AppComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomerNotesRoute = AppCustomerNotesRouteImport.update({
  id: '/customer-notes',
  path: '/customer-notes',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppDangerZoneRoute = AppDangerZoneRouteImport.update({
  id: '/danger-zone',
  path: '/danger-zone',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveryRoute = AppDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailMarketingRoute = AppEmailMarketingRouteImport.update({
  id: '/email-marketing',
  path: '/email-marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppEmbedFormsRoute = AppEmbedFormsRouteImport.update({
  id: '/embed-forms',
  path: '/embed-forms',
  getParentRoute: () => AppRoute,
} as any)
const AppFaultyStockRoute = AppFaultyStockRouteImport.update({
  id: '/faulty-stock',
  path: '/faulty-stock',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceLedgerRoute = AppFinanceLedgerRouteImport.update({
  id: '/finance-ledger',
  path: '/finance-ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowUpsRoute = AppFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AppRoute,
} as any)
const AppFormSubmissionsRoute = AppFormSubmissionsRouteImport.update({
  id: '/form-submissions',
  path: '/form-submissions',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsRoute = AppFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppMessageTemplatesRoute = AppMessageTemplatesRouteImport.update({
  id: '/message-templates',
  path: '/message-templates',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppProductAnalyticsRoute = AppProductAnalyticsRouteImport.update({
  id: '/product-analytics',
  path: '/product-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppProfitDashboardRoute = AppProfitDashboardRouteImport.update({
  id: '/profit-dashboard',
  path: '/profit-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPromoterTargetsRoute = AppPromoterTargetsRouteImport.update({
  id: '/promoter-targets',
  path: '/promoter-targets',
  getParentRoute: () => AppRoute,
} as any)
const AppPromotersRoute = AppPromotersRouteImport.update({
  id: '/promoters',
  path: '/promoters',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppReturnsRoute = AppReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesPermissionsRoute = AppRolesPermissionsRouteImport.update({
  id: '/roles-permissions',
  path: '/roles-permissions',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesCohortsRoute = AppSalesCohortsRouteImport.update({
  id: '/sales-cohorts',
  path: '/sales-cohorts',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesManagerOfficeRoute = AppSalesManagerOfficeRouteImport.update({
  id: '/sales-manager-office',
  path: '/sales-manager-office',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSmsAutomationRoute = AppSmsAutomationRouteImport.update({
  id: '/sms-automation',
  path: '/sms-automation',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffEarningsRoute = AppStaffEarningsRouteImport.update({
  id: '/staff-earnings',
  path: '/staff-earnings',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffPerformanceRoute = AppStaffPerformanceRouteImport.update({
  id: '/staff-performance',
  path: '/staff-performance',
  getParentRoute: () => AppRoute,
} as any)
const AppStateWhatsappGroupsRoute = AppStateWhatsappGroupsRouteImport.update({
  id: '/state-whatsapp-groups',
  path: '/state-whatsapp-groups',
  getParentRoute: () => AppRoute,
} as any)
const AppStockRecordRoute = AppStockRecordRouteImport.update({
  id: '/stock-record',
  path: '/stock-record',
  getParentRoute: () => AppRoute,
} as any)
const AppStorefrontRoute = AppStorefrontRouteImport.update({
  id: '/storefront',
  path: '/storefront',
  getParentRoute: () => AppRoute,
} as any)
const AppStorefrontCustomizationRoute =
  AppStorefrontCustomizationRouteImport.update({
    id: '/storefront-customization',
    path: '/storefront-customization',
    getParentRoute: () => AppRoute,
  } as any)
const AppTrackingRoute = AppTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppWaybillRoute = AppWaybillRouteImport.update({
  id: '/waybill',
  path: '/waybill',
  getParentRoute: () => AppRoute,
} as any)
const AppWhatsappAutomationRoute = AppWhatsappAutomationRouteImport.update({
  id: '/whatsapp-automation',
  path: '/whatsapp-automation',
  getParentRoute: () => AppRoute,
} as any)
const FormSlugRoute = FormSlugRouteImport.update({
  id: '/form/$slug',
  path: '/form/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemCreateOwnerRoute = SystemCreateOwnerRouteImport.update({
  id: '/system/create-owner',
  path: '/system/create-owner',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderCodeRoute = TrackOrderCodeRouteImport.update({
  id: '/track/$orderCode',
  path: '/track/$orderCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AppConnectionsAiProviderRoute =
  AppConnectionsAiProviderRouteImport.update({
    id: '/connections/ai-provider',
    path: '/connections/ai-provider',
    getParentRoute: () => AppRoute,
  } as any)
const AppConnectionsElementorRoute = AppConnectionsElementorRouteImport.update({
  id: '/connections/elementor',
  path: '/connections/elementor',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsEmailRoute = AppConnectionsEmailRouteImport.update({
  id: '/connections/email',
  path: '/connections/email',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsPaymentGatewaysRoute =
  AppConnectionsPaymentGatewaysRouteImport.update({
    id: '/connections/payment-gateways',
    path: '/connections/payment-gateways',
    getParentRoute: () => AppRoute,
  } as any)
const AppConnectionsSmsRoute = AppConnectionsSmsRouteImport.update({
  id: '/connections/sms',
  path: '/connections/sms',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsWebhooksRoute = AppConnectionsWebhooksRouteImport.update({
  id: '/connections/webhooks',
  path: '/connections/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsWhatsappRoute = AppConnectionsWhatsappRouteImport.update({
  id: '/connections/whatsapp',
  path: '/connections/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsWoocommerceRoute =
  AppConnectionsWoocommerceRouteImport.update({
    id: '/connections/woocommerce',
    path: '/connections/woocommerce',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/abandoned-cart': typeof AppAbandonedCartRoute
  '/activity-logs': typeof AppActivityLogsRoute
  '/affiliates': typeof AppAffiliatesRoute
  '/agent-deliveries': typeof AppAgentDeliveriesRoute
  '/agent-performance': typeof AppAgentPerformanceRoute
  '/agent-stock': typeof AppAgentStockRoute
  '/agents': typeof AppAgentsRoute
  '/ai': typeof AppAiRoute
  '/api-test-center': typeof AppApiTestCenterRoute
  '/assignment-rules': typeof AppAssignmentRulesRoute
  '/broadcast-history': typeof AppBroadcastHistoryRoute
  '/buy-stock': typeof AppBuyStockRoute
  '/call-logs': typeof AppCallLogsRoute
  '/call-queue': typeof AppCallQueueRoute
  '/campaign-attribution': typeof AppCampaignAttributionRoute
  '/campaigns': typeof AppCampaignsRoute
  '/chat': typeof AppChatRoute
  '/checkout': typeof AppCheckoutRoute
  '/complaints': typeof AppComplaintsRoute
  '/customer-notes': typeof AppCustomerNotesRoute
  '/customers': typeof AppCustomersRoute
  '/danger-zone': typeof AppDangerZoneRoute
  '/dashboard': typeof AppDashboardRoute
  '/delivery': typeof AppDeliveryRoute
  '/email-marketing': typeof AppEmailMarketingRoute
  '/embed-forms': typeof AppEmbedFormsRoute
  '/faulty-stock': typeof AppFaultyStockRoute
  '/finance': typeof AppFinanceRoute
  '/finance-ledger': typeof AppFinanceLedgerRoute
  '/follow-ups': typeof AppFollowUpsRoute
  '/form-submissions': typeof AppFormSubmissionsRoute
  '/forms': typeof AppFormsRoute
  '/inventory': typeof AppInventoryRoute
  '/message-templates': typeof AppMessageTemplatesRoute
  '/notifications': typeof AppNotificationsRoute
  '/orders': typeof AppOrdersRouteWithChildren
  '/product-analytics': typeof AppProductAnalyticsRoute
  '/products': typeof AppProductsRoute
  '/profit-dashboard': typeof AppProfitDashboardRoute
  '/promoter-targets': typeof AppPromoterTargetsRoute
  '/promoters': typeof AppPromotersRoute
  '/reports': typeof AppReportsRoute
  '/returns': typeof AppReturnsRoute
  '/roles-permissions': typeof AppRolesPermissionsRoute
  '/sales-cohorts': typeof AppSalesCohortsRoute
  '/sales-manager-office': typeof AppSalesManagerOfficeRoute
  '/settings': typeof AppSettingsRoute
  '/sms-automation': typeof AppSmsAutomationRoute
  '/staff': typeof AppStaffRoute
  '/staff-earnings': typeof AppStaffEarningsRoute
  '/staff-performance': typeof AppStaffPerformanceRoute
  '/state-whatsapp-groups': typeof AppStateWhatsappGroupsRoute
  '/stock-record': typeof AppStockRecordRoute
  '/storefront': typeof AppStorefrontRoute
  '/storefront-customization': typeof AppStorefrontCustomizationRoute
  '/tracking': typeof AppTrackingRoute
  '/wallet': typeof AppWalletRoute
  '/waybill': typeof AppWaybillRoute
  '/whatsapp-automation': typeof AppWhatsappAutomationRoute
  '/form/$slug': typeof FormSlugRoute
  '/system/create-owner': typeof SystemCreateOwnerRoute
  '/track/$orderCode': typeof TrackOrderCodeRoute
  '/connections/ai-provider': typeof AppConnectionsAiProviderRoute
  '/connections/elementor': typeof AppConnectionsElementorRoute
  '/connections/email': typeof AppConnectionsEmailRoute
  '/connections/payment-gateways': typeof AppConnectionsPaymentGatewaysRoute
  '/connections/sms': typeof AppConnectionsSmsRoute
  '/connections/webhooks': typeof AppConnectionsWebhooksRoute
  '/connections/whatsapp': typeof AppConnectionsWhatsappRoute
  '/connections/woocommerce': typeof AppConnectionsWoocommerceRoute
  '/orders/$id': typeof AppOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/abandoned-cart': typeof AppAbandonedCartRoute
  '/activity-logs': typeof AppActivityLogsRoute
  '/affiliates': typeof AppAffiliatesRoute
  '/agent-deliveries': typeof AppAgentDeliveriesRoute
  '/agent-performance': typeof AppAgentPerformanceRoute
  '/agent-stock': typeof AppAgentStockRoute
  '/agents': typeof AppAgentsRoute
  '/ai': typeof AppAiRoute
  '/api-test-center': typeof AppApiTestCenterRoute
  '/assignment-rules': typeof AppAssignmentRulesRoute
  '/broadcast-history': typeof AppBroadcastHistoryRoute
  '/buy-stock': typeof AppBuyStockRoute
  '/call-logs': typeof AppCallLogsRoute
  '/call-queue': typeof AppCallQueueRoute
  '/campaign-attribution': typeof AppCampaignAttributionRoute
  '/campaigns': typeof AppCampaignsRoute
  '/chat': typeof AppChatRoute
  '/checkout': typeof AppCheckoutRoute
  '/complaints': typeof AppComplaintsRoute
  '/customer-notes': typeof AppCustomerNotesRoute
  '/customers': typeof AppCustomersRoute
  '/danger-zone': typeof AppDangerZoneRoute
  '/dashboard': typeof AppDashboardRoute
  '/delivery': typeof AppDeliveryRoute
  '/email-marketing': typeof AppEmailMarketingRoute
  '/embed-forms': typeof AppEmbedFormsRoute
  '/faulty-stock': typeof AppFaultyStockRoute
  '/finance': typeof AppFinanceRoute
  '/finance-ledger': typeof AppFinanceLedgerRoute
  '/follow-ups': typeof AppFollowUpsRoute
  '/form-submissions': typeof AppFormSubmissionsRoute
  '/forms': typeof AppFormsRoute
  '/inventory': typeof AppInventoryRoute
  '/message-templates': typeof AppMessageTemplatesRoute
  '/notifications': typeof AppNotificationsRoute
  '/orders': typeof AppOrdersRouteWithChildren
  '/product-analytics': typeof AppProductAnalyticsRoute
  '/products': typeof AppProductsRoute
  '/profit-dashboard': typeof AppProfitDashboardRoute
  '/promoter-targets': typeof AppPromoterTargetsRoute
  '/promoters': typeof AppPromotersRoute
  '/reports': typeof AppReportsRoute
  '/returns': typeof AppReturnsRoute
  '/roles-permissions': typeof AppRolesPermissionsRoute
  '/sales-cohorts': typeof AppSalesCohortsRoute
  '/sales-manager-office': typeof AppSalesManagerOfficeRoute
  '/settings': typeof AppSettingsRoute
  '/sms-automation': typeof AppSmsAutomationRoute
  '/staff': typeof AppStaffRoute
  '/staff-earnings': typeof AppStaffEarningsRoute
  '/staff-performance': typeof AppStaffPerformanceRoute
  '/state-whatsapp-groups': typeof AppStateWhatsappGroupsRoute
  '/stock-record': typeof AppStockRecordRoute
  '/storefront': typeof AppStorefrontRoute
  '/storefront-customization': typeof AppStorefrontCustomizationRoute
  '/tracking': typeof AppTrackingRoute
  '/wallet': typeof AppWalletRoute
  '/waybill': typeof AppWaybillRoute
  '/whatsapp-automation': typeof AppWhatsappAutomationRoute
  '/form/$slug': typeof FormSlugRoute
  '/system/create-owner': typeof SystemCreateOwnerRoute
  '/track/$orderCode': typeof TrackOrderCodeRoute
  '/connections/ai-provider': typeof AppConnectionsAiProviderRoute
  '/connections/elementor': typeof AppConnectionsElementorRoute
  '/connections/email': typeof AppConnectionsEmailRoute
  '/connections/payment-gateways': typeof AppConnectionsPaymentGatewaysRoute
  '/connections/sms': typeof AppConnectionsSmsRoute
  '/connections/webhooks': typeof AppConnectionsWebhooksRoute
  '/connections/whatsapp': typeof AppConnectionsWhatsappRoute
  '/connections/woocommerce': typeof AppConnectionsWoocommerceRoute
  '/orders/$id': typeof AppOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/abandoned-cart': typeof AppAbandonedCartRoute
  '/_app/activity-logs': typeof AppActivityLogsRoute
  '/_app/affiliates': typeof AppAffiliatesRoute
  '/_app/agent-deliveries': typeof AppAgentDeliveriesRoute
  '/_app/agent-performance': typeof AppAgentPerformanceRoute
  '/_app/agent-stock': typeof AppAgentStockRoute
  '/_app/agents': typeof AppAgentsRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/api-test-center': typeof AppApiTestCenterRoute
  '/_app/assignment-rules': typeof AppAssignmentRulesRoute
  '/_app/broadcast-history': typeof AppBroadcastHistoryRoute
  '/_app/buy-stock': typeof AppBuyStockRoute
  '/_app/call-logs': typeof AppCallLogsRoute
  '/_app/call-queue': typeof AppCallQueueRoute
  '/_app/campaign-attribution': typeof AppCampaignAttributionRoute
  '/_app/campaigns': typeof AppCampaignsRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/checkout': typeof AppCheckoutRoute
  '/_app/complaints': typeof AppComplaintsRoute
  '/_app/customer-notes': typeof AppCustomerNotesRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/danger-zone': typeof AppDangerZoneRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/delivery': typeof AppDeliveryRoute
  '/_app/email-marketing': typeof AppEmailMarketingRoute
  '/_app/embed-forms': typeof AppEmbedFormsRoute
  '/_app/faulty-stock': typeof AppFaultyStockRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/finance-ledger': typeof AppFinanceLedgerRoute
  '/_app/follow-ups': typeof AppFollowUpsRoute
  '/_app/form-submissions': typeof AppFormSubmissionsRoute
  '/_app/forms': typeof AppFormsRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/message-templates': typeof AppMessageTemplatesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/orders': typeof AppOrdersRouteWithChildren
  '/_app/product-analytics': typeof AppProductAnalyticsRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/profit-dashboard': typeof AppProfitDashboardRoute
  '/_app/promoter-targets': typeof AppPromoterTargetsRoute
  '/_app/promoters': typeof AppPromotersRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/returns': typeof AppReturnsRoute
  '/_app/roles-permissions': typeof AppRolesPermissionsRoute
  '/_app/sales-cohorts': typeof AppSalesCohortsRoute
  '/_app/sales-manager-office': typeof AppSalesManagerOfficeRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sms-automation': typeof AppSmsAutomationRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/staff-earnings': typeof AppStaffEarningsRoute
  '/_app/staff-performance': typeof AppStaffPerformanceRoute
  '/_app/state-whatsapp-groups': typeof AppStateWhatsappGroupsRoute
  '/_app/stock-record': typeof AppStockRecordRoute
  '/_app/storefront': typeof AppStorefrontRoute
  '/_app/storefront-customization': typeof AppStorefrontCustomizationRoute
  '/_app/tracking': typeof AppTrackingRoute
  '/_app/wallet': typeof AppWalletRoute
  '/_app/waybill': typeof AppWaybillRoute
  '/_app/whatsapp-automation': typeof AppWhatsappAutomationRoute
  '/form/$slug': typeof FormSlugRoute
  '/system/create-owner': typeof SystemCreateOwnerRoute
  '/track/$orderCode': typeof TrackOrderCodeRoute
  '/_app/connections/ai-provider': typeof AppConnectionsAiProviderRoute
  '/_app/connections/elementor': typeof AppConnectionsElementorRoute
  '/_app/connections/email': typeof AppConnectionsEmailRoute
  '/_app/connections/payment-gateways': typeof AppConnectionsPaymentGatewaysRoute
  '/_app/connections/sms': typeof AppConnectionsSmsRoute
  '/_app/connections/webhooks': typeof AppConnectionsWebhooksRoute
  '/_app/connections/whatsapp': typeof AppConnectionsWhatsappRoute
  '/_app/connections/woocommerce': typeof AppConnectionsWoocommerceRoute
  '/_app/orders/$id': typeof AppOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/abandoned-cart'
    | '/activity-logs'
    | '/affiliates'
    | '/agent-deliveries'
    | '/agent-performance'
    | '/agent-stock'
    | '/agents'
    | '/ai'
    | '/api-test-center'
    | '/assignment-rules'
    | '/broadcast-history'
    | '/buy-stock'
    | '/call-logs'
    | '/call-queue'
    | '/campaign-attribution'
    | '/campaigns'
    | '/chat'
    | '/checkout'
    | '/complaints'
    | '/customer-notes'
    | '/customers'
    | '/danger-zone'
    | '/dashboard'
    | '/delivery'
    | '/email-marketing'
    | '/embed-forms'
    | '/faulty-stock'
    | '/finance'
    | '/finance-ledger'
    | '/follow-ups'
    | '/form-submissions'
    | '/forms'
    | '/inventory'
    | '/message-templates'
    | '/notifications'
    | '/orders'
    | '/product-analytics'
    | '/products'
    | '/profit-dashboard'
    | '/promoter-targets'
    | '/promoters'
    | '/reports'
    | '/returns'
    | '/roles-permissions'
    | '/sales-cohorts'
    | '/sales-manager-office'
    | '/settings'
    | '/sms-automation'
    | '/staff'
    | '/staff-earnings'
    | '/staff-performance'
    | '/state-whatsapp-groups'
    | '/stock-record'
    | '/storefront'
    | '/storefront-customization'
    | '/tracking'
    | '/wallet'
    | '/waybill'
    | '/whatsapp-automation'
    | '/form/$slug'
    | '/system/create-owner'
    | '/track/$orderCode'
    | '/connections/ai-provider'
    | '/connections/elementor'
    | '/connections/email'
    | '/connections/payment-gateways'
    | '/connections/sms'
    | '/connections/webhooks'
    | '/connections/whatsapp'
    | '/connections/woocommerce'
    | '/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/abandoned-cart'
    | '/activity-logs'
    | '/affiliates'
    | '/agent-deliveries'
    | '/agent-performance'
    | '/agent-stock'
    | '/agents'
    | '/ai'
    | '/api-test-center'
    | '/assignment-rules'
    | '/broadcast-history'
    | '/buy-stock'
    | '/call-logs'
    | '/call-queue'
    | '/campaign-attribution'
    | '/campaigns'
    | '/chat'
    | '/checkout'
    | '/complaints'
    | '/customer-notes'
    | '/customers'
    | '/danger-zone'
    | '/dashboard'
    | '/delivery'
    | '/email-marketing'
    | '/embed-forms'
    | '/faulty-stock'
    | '/finance'
    | '/finance-ledger'
    | '/follow-ups'
    | '/form-submissions'
    | '/forms'
    | '/inventory'
    | '/message-templates'
    | '/notifications'
    | '/orders'
    | '/product-analytics'
    | '/products'
    | '/profit-dashboard'
    | '/promoter-targets'
    | '/promoters'
    | '/reports'
    | '/returns'
    | '/roles-permissions'
    | '/sales-cohorts'
    | '/sales-manager-office'
    | '/settings'
    | '/sms-automation'
    | '/staff'
    | '/staff-earnings'
    | '/staff-performance'
    | '/state-whatsapp-groups'
    | '/stock-record'
    | '/storefront'
    | '/storefront-customization'
    | '/tracking'
    | '/wallet'
    | '/waybill'
    | '/whatsapp-automation'
    | '/form/$slug'
    | '/system/create-owner'
    | '/track/$orderCode'
    | '/connections/ai-provider'
    | '/connections/elementor'
    | '/connections/email'
    | '/connections/payment-gateways'
    | '/connections/sms'
    | '/connections/webhooks'
    | '/connections/whatsapp'
    | '/connections/woocommerce'
    | '/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/abandoned-cart'
    | '/_app/activity-logs'
    | '/_app/affiliates'
    | '/_app/agent-deliveries'
    | '/_app/agent-performance'
    | '/_app/agent-stock'
    | '/_app/agents'
    | '/_app/ai'
    | '/_app/api-test-center'
    | '/_app/assignment-rules'
    | '/_app/broadcast-history'
    | '/_app/buy-stock'
    | '/_app/call-logs'
    | '/_app/call-queue'
    | '/_app/campaign-attribution'
    | '/_app/campaigns'
    | '/_app/chat'
    | '/_app/checkout'
    | '/_app/complaints'
    | '/_app/customer-notes'
    | '/_app/customers'
    | '/_app/danger-zone'
    | '/_app/dashboard'
    | '/_app/delivery'
    | '/_app/email-marketing'
    | '/_app/embed-forms'
    | '/_app/faulty-stock'
    | '/_app/finance'
    | '/_app/finance-ledger'
    | '/_app/follow-ups'
    | '/_app/form-submissions'
    | '/_app/forms'
    | '/_app/inventory'
    | '/_app/message-templates'
    | '/_app/notifications'
    | '/_app/orders'
    | '/_app/product-analytics'
    | '/_app/products'
    | '/_app/profit-dashboard'
    | '/_app/promoter-targets'
    | '/_app/promoters'
    | '/_app/reports'
    | '/_app/returns'
    | '/_app/roles-permissions'
    | '/_app/sales-cohorts'
    | '/_app/sales-manager-office'
    | '/_app/settings'
    | '/_app/sms-automation'
    | '/_app/staff'
    | '/_app/staff-earnings'
    | '/_app/staff-performance'
    | '/_app/state-whatsapp-groups'
    | '/_app/stock-record'
    | '/_app/storefront'
    | '/_app/storefront-customization'
    | '/_app/tracking'
    | '/_app/wallet'
    | '/_app/waybill'
    | '/_app/whatsapp-automation'
    | '/form/$slug'
    | '/system/create-owner'
    | '/track/$orderCode'
    | '/_app/connections/ai-provider'
    | '/_app/connections/elementor'
    | '/_app/connections/email'
    | '/_app/connections/payment-gateways'
    | '/_app/connections/sms'
    | '/_app/connections/webhooks'
    | '/_app/connections/whatsapp'
    | '/_app/connections/woocommerce'
    | '/_app/orders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  FormSlugRoute: typeof FormSlugRoute
  SystemCreateOwnerRoute: typeof SystemCreateOwnerRoute
  TrackOrderCodeRoute: typeof TrackOrderCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/abandoned-cart': {
      id: '/_app/abandoned-cart'
      path: '/abandoned-cart'
      fullPath: '/abandoned-cart'
      preLoaderRoute: typeof AppAbandonedCartRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity-logs': {
      id: '/_app/activity-logs'
      path: '/activity-logs'
      fullPath: '/activity-logs'
      preLoaderRoute: typeof AppActivityLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affiliates': {
      id: '/_app/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AppAffiliatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent-deliveries': {
      id: '/_app/agent-deliveries'
      path: '/agent-deliveries'
      fullPath: '/agent-deliveries'
      preLoaderRoute: typeof AppAgentDeliveriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent-performance': {
      id: '/_app/agent-performance'
      path: '/agent-performance'
      fullPath: '/agent-performance'
      preLoaderRoute: typeof AppAgentPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent-stock': {
      id: '/_app/agent-stock'
      path: '/agent-stock'
      fullPath: '/agent-stock'
      preLoaderRoute: typeof AppAgentStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api-test-center': {
      id: '/_app/api-test-center'
      path: '/api-test-center'
      fullPath: '/api-test-center'
      preLoaderRoute: typeof AppApiTestCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assignment-rules': {
      id: '/_app/assignment-rules'
      path: '/assignment-rules'
      fullPath: '/assignment-rules'
      preLoaderRoute: typeof AppAssignmentRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/broadcast-history': {
      id: '/_app/broadcast-history'
      path: '/broadcast-history'
      fullPath: '/broadcast-history'
      preLoaderRoute: typeof AppBroadcastHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buy-stock': {
      id: '/_app/buy-stock'
      path: '/buy-stock'
      fullPath: '/buy-stock'
      preLoaderRoute: typeof AppBuyStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/call-logs': {
      id: '/_app/call-logs'
      path: '/call-logs'
      fullPath: '/call-logs'
      preLoaderRoute: typeof AppCallLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/call-queue': {
      id: '/_app/call-queue'
      path: '/call-queue'
      fullPath: '/call-queue'
      preLoaderRoute: typeof AppCallQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaign-attribution': {
      id: '/_app/campaign-attribution'
      path: '/campaign-attribution'
      fullPath: '/campaign-attribution'
      preLoaderRoute: typeof AppCampaignAttributionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkout': {
      id: '/_app/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/complaints': {
      id: '/_app/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AppComplaintsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customer-notes': {
      id: '/_app/customer-notes'
      path: '/customer-notes'
      fullPath: '/customer-notes'
      preLoaderRoute: typeof AppCustomerNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/danger-zone': {
      id: '/_app/danger-zone'
      path: '/danger-zone'
      fullPath: '/danger-zone'
      preLoaderRoute: typeof AppDangerZoneRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/delivery': {
      id: '/_app/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof AppDeliveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/email-marketing': {
      id: '/_app/email-marketing'
      path: '/email-marketing'
      fullPath: '/email-marketing'
      preLoaderRoute: typeof AppEmailMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/embed-forms': {
      id: '/_app/embed-forms'
      path: '/embed-forms'
      fullPath: '/embed-forms'
      preLoaderRoute: typeof AppEmbedFormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/faulty-stock': {
      id: '/_app/faulty-stock'
      path: '/faulty-stock'
      fullPath: '/faulty-stock'
      preLoaderRoute: typeof AppFaultyStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance-ledger': {
      id: '/_app/finance-ledger'
      path: '/finance-ledger'
      fullPath: '/finance-ledger'
      preLoaderRoute: typeof AppFinanceLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/follow-ups': {
      id: '/_app/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof AppFollowUpsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/form-submissions': {
      id: '/_app/form-submissions'
      path: '/form-submissions'
      fullPath: '/form-submissions'
      preLoaderRoute: typeof AppFormSubmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forms': {
      id: '/_app/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AppFormsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/message-templates': {
      id: '/_app/message-templates'
      path: '/message-templates'
      fullPath: '/message-templates'
      preLoaderRoute: typeof AppMessageTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/product-analytics': {
      id: '/_app/product-analytics'
      path: '/product-analytics'
      fullPath: '/product-analytics'
      preLoaderRoute: typeof AppProductAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profit-dashboard': {
      id: '/_app/profit-dashboard'
      path: '/profit-dashboard'
      fullPath: '/profit-dashboard'
      preLoaderRoute: typeof AppProfitDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/promoter-targets': {
      id: '/_app/promoter-targets'
      path: '/promoter-targets'
      fullPath: '/promoter-targets'
      preLoaderRoute: typeof AppPromoterTargetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/promoters': {
      id: '/_app/promoters'
      path: '/promoters'
      fullPath: '/promoters'
      preLoaderRoute: typeof AppPromotersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/returns': {
      id: '/_app/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof AppReturnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles-permissions': {
      id: '/_app/roles-permissions'
      path: '/roles-permissions'
      fullPath: '/roles-permissions'
      preLoaderRoute: typeof AppRolesPermissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales-cohorts': {
      id: '/_app/sales-cohorts'
      path: '/sales-cohorts'
      fullPath: '/sales-cohorts'
      preLoaderRoute: typeof AppSalesCohortsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales-manager-office': {
      id: '/_app/sales-manager-office'
      path: '/sales-manager-office'
      fullPath: '/sales-manager-office'
      preLoaderRoute: typeof AppSalesManagerOfficeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sms-automation': {
      id: '/_app/sms-automation'
      path: '/sms-automation'
      fullPath: '/sms-automation'
      preLoaderRoute: typeof AppSmsAutomationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff-earnings': {
      id: '/_app/staff-earnings'
      path: '/staff-earnings'
      fullPath: '/staff-earnings'
      preLoaderRoute: typeof AppStaffEarningsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff-performance': {
      id: '/_app/staff-performance'
      path: '/staff-performance'
      fullPath: '/staff-performance'
      preLoaderRoute: typeof AppStaffPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/state-whatsapp-groups': {
      id: '/_app/state-whatsapp-groups'
      path: '/state-whatsapp-groups'
      fullPath: '/state-whatsapp-groups'
      preLoaderRoute: typeof AppStateWhatsappGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock-record': {
      id: '/_app/stock-record'
      path: '/stock-record'
      fullPath: '/stock-record'
      preLoaderRoute: typeof AppStockRecordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/storefront': {
      id: '/_app/storefront'
      path: '/storefront'
      fullPath: '/storefront'
      preLoaderRoute: typeof AppStorefrontRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/storefront-customization': {
      id: '/_app/storefront-customization'
      path: '/storefront-customization'
      fullPath: '/storefront-customization'
      preLoaderRoute: typeof AppStorefrontCustomizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracking': {
      id: '/_app/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof AppTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/waybill': {
      id: '/_app/waybill'
      path: '/waybill'
      fullPath: '/waybill'
      preLoaderRoute: typeof AppWaybillRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/whatsapp-automation': {
      id: '/_app/whatsapp-automation'
      path: '/whatsapp-automation'
      fullPath: '/whatsapp-automation'
      preLoaderRoute: typeof AppWhatsappAutomationRouteImport
      parentRoute: typeof AppRoute
    }
    '/form/$slug': {
      id: '/form/$slug'
      path: '/form/$slug'
      fullPath: '/form/$slug'
      preLoaderRoute: typeof FormSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/create-owner': {
      id: '/system/create-owner'
      path: '/system/create-owner'
      fullPath: '/system/create-owner'
      preLoaderRoute: typeof SystemCreateOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$orderCode': {
      id: '/track/$orderCode'
      path: '/track/$orderCode'
      fullPath: '/track/$orderCode'
      preLoaderRoute: typeof TrackOrderCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/connections/ai-provider': {
      id: '/_app/connections/ai-provider'
      path: '/connections/ai-provider'
      fullPath: '/connections/ai-provider'
      preLoaderRoute: typeof AppConnectionsAiProviderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections/elementor': {
      id: '/_app/connections/elementor'
      path: '/connections/elementor'
      fullPath: '/connections/elementor'
      preLoaderRoute: typeof AppConnectionsElementorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections/email': {
      id: '/_app/connections/email'
      path: '/connections/email'
      fullPath: '/connections/email'
      preLoaderRoute: typeof AppConnectionsEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections/payment-gateways': {
      id: '/_app/connections/payment-gateways'
      path: '/connections/payment-gateways'
      fullPath: '/connections/payment-gateways'
      preLoaderRoute: typeof AppConnectionsPaymentGatewaysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections/sms': {
      id: '/_app/connections/sms'
      path: '/connections/sms'
      fullPath: '/connections/sms'
      preLoaderRoute: typeof AppConnectionsSmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections/webhooks': {
      id: '/_app/connections/webhooks'
      path: '/connections/webhooks'
      fullPath: '/connections/webhooks'
      preLoaderRoute: typeof AppConnectionsWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections/whatsapp': {
      id: '/_app/connections/whatsapp'
      path: '/connections/whatsapp'
      fullPath: '/connections/whatsapp'
      preLoaderRoute: typeof AppConnectionsWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections/woocommerce': {
      id: '/_app/connections/woocommerce'
      path: '/connections/woocommerce'
      fullPath: '/connections/woocommerce'
      preLoaderRoute: typeof AppConnectionsWoocommerceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$id': {
      id: '/_app/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppOrdersRoute
    }
  }
}

interface AppOrdersRouteChildren {
  AppOrdersIdRoute: typeof AppOrdersIdRoute
}

const AppOrdersRouteChildren: AppOrdersRouteChildren = {
  AppOrdersIdRoute: AppOrdersIdRoute,
}

const AppOrdersRouteWithChildren = AppOrdersRoute._addFileChildren(
  AppOrdersRouteChildren,
)

interface AppRouteChildren {
  AppAbandonedCartRoute: typeof AppAbandonedCartRoute
  AppActivityLogsRoute: typeof AppActivityLogsRoute
  AppAffiliatesRoute: typeof AppAffiliatesRoute
  AppAgentDeliveriesRoute: typeof AppAgentDeliveriesRoute
  AppAgentPerformanceRoute: typeof AppAgentPerformanceRoute
  AppAgentStockRoute: typeof AppAgentStockRoute
  AppAgentsRoute: typeof AppAgentsRoute
  AppAiRoute: typeof AppAiRoute
  AppApiTestCenterRoute: typeof AppApiTestCenterRoute
  AppAssignmentRulesRoute: typeof AppAssignmentRulesRoute
  AppBroadcastHistoryRoute: typeof AppBroadcastHistoryRoute
  AppBuyStockRoute: typeof AppBuyStockRoute
  AppCallLogsRoute: typeof AppCallLogsRoute
  AppCallQueueRoute: typeof AppCallQueueRoute
  AppCampaignAttributionRoute: typeof AppCampaignAttributionRoute
  AppCampaignsRoute: typeof AppCampaignsRoute
  AppChatRoute: typeof AppChatRoute
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppComplaintsRoute: typeof AppComplaintsRoute
  AppCustomerNotesRoute: typeof AppCustomerNotesRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDangerZoneRoute: typeof AppDangerZoneRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDeliveryRoute: typeof AppDeliveryRoute
  AppEmailMarketingRoute: typeof AppEmailMarketingRoute
  AppEmbedFormsRoute: typeof AppEmbedFormsRoute
  AppFaultyStockRoute: typeof AppFaultyStockRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppFinanceLedgerRoute: typeof AppFinanceLedgerRoute
  AppFollowUpsRoute: typeof AppFollowUpsRoute
  AppFormSubmissionsRoute: typeof AppFormSubmissionsRoute
  AppFormsRoute: typeof AppFormsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppMessageTemplatesRoute: typeof AppMessageTemplatesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrdersRoute: typeof AppOrdersRouteWithChildren
  AppProductAnalyticsRoute: typeof AppProductAnalyticsRoute
  AppProductsRoute: typeof AppProductsRoute
  AppProfitDashboardRoute: typeof AppProfitDashboardRoute
  AppPromoterTargetsRoute: typeof AppPromoterTargetsRoute
  AppPromotersRoute: typeof AppPromotersRoute
  AppReportsRoute: typeof AppReportsRoute
  AppReturnsRoute: typeof AppReturnsRoute
  AppRolesPermissionsRoute: typeof AppRolesPermissionsRoute
  AppSalesCohortsRoute: typeof AppSalesCohortsRoute
  AppSalesManagerOfficeRoute: typeof AppSalesManagerOfficeRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSmsAutomationRoute: typeof AppSmsAutomationRoute
  AppStaffRoute: typeof AppStaffRoute
  AppStaffEarningsRoute: typeof AppStaffEarningsRoute
  AppStaffPerformanceRoute: typeof AppStaffPerformanceRoute
  AppStateWhatsappGroupsRoute: typeof AppStateWhatsappGroupsRoute
  AppStockRecordRoute: typeof AppStockRecordRoute
  AppStorefrontRoute: typeof AppStorefrontRoute
  AppStorefrontCustomizationRoute: typeof AppStorefrontCustomizationRoute
  AppTrackingRoute: typeof AppTrackingRoute
  AppWalletRoute: typeof AppWalletRoute
  AppWaybillRoute: typeof AppWaybillRoute
  AppWhatsappAutomationRoute: typeof AppWhatsappAutomationRoute
  AppConnectionsAiProviderRoute: typeof AppConnectionsAiProviderRoute
  AppConnectionsElementorRoute: typeof AppConnectionsElementorRoute
  AppConnectionsEmailRoute: typeof AppConnectionsEmailRoute
  AppConnectionsPaymentGatewaysRoute: typeof AppConnectionsPaymentGatewaysRoute
  AppConnectionsSmsRoute: typeof AppConnectionsSmsRoute
  AppConnectionsWebhooksRoute: typeof AppConnectionsWebhooksRoute
  AppConnectionsWhatsappRoute: typeof AppConnectionsWhatsappRoute
  AppConnectionsWoocommerceRoute: typeof AppConnectionsWoocommerceRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAbandonedCartRoute: AppAbandonedCartRoute,
  AppActivityLogsRoute: AppActivityLogsRoute,
  AppAffiliatesRoute: AppAffiliatesRoute,
  AppAgentDeliveriesRoute: AppAgentDeliveriesRoute,
  AppAgentPerformanceRoute: AppAgentPerformanceRoute,
  AppAgentStockRoute: AppAgentStockRoute,
  AppAgentsRoute: AppAgentsRoute,
  AppAiRoute: AppAiRoute,
  AppApiTestCenterRoute: AppApiTestCenterRoute,
  AppAssignmentRulesRoute: AppAssignmentRulesRoute,
  AppBroadcastHistoryRoute: AppBroadcastHistoryRoute,
  AppBuyStockRoute: AppBuyStockRoute,
  AppCallLogsRoute: AppCallLogsRoute,
  AppCallQueueRoute: AppCallQueueRoute,
  AppCampaignAttributionRoute: AppCampaignAttributionRoute,
  AppCampaignsRoute: AppCampaignsRoute,
  AppChatRoute: AppChatRoute,
  AppCheckoutRoute: AppCheckoutRoute,
  AppComplaintsRoute: AppComplaintsRoute,
  AppCustomerNotesRoute: AppCustomerNotesRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDangerZoneRoute: AppDangerZoneRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDeliveryRoute: AppDeliveryRoute,
  AppEmailMarketingRoute: AppEmailMarketingRoute,
  AppEmbedFormsRoute: AppEmbedFormsRoute,
  AppFaultyStockRoute: AppFaultyStockRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppFinanceLedgerRoute: AppFinanceLedgerRoute,
  AppFollowUpsRoute: AppFollowUpsRoute,
  AppFormSubmissionsRoute: AppFormSubmissionsRoute,
  AppFormsRoute: AppFormsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppMessageTemplatesRoute: AppMessageTemplatesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrdersRoute: AppOrdersRouteWithChildren,
  AppProductAnalyticsRoute: AppProductAnalyticsRoute,
  AppProductsRoute: AppProductsRoute,
  AppProfitDashboardRoute: AppProfitDashboardRoute,
  AppPromoterTargetsRoute: AppPromoterTargetsRoute,
  AppPromotersRoute: AppPromotersRoute,
  AppReportsRoute: AppReportsRoute,
  AppReturnsRoute: AppReturnsRoute,
  AppRolesPermissionsRoute: AppRolesPermissionsRoute,
  AppSalesCohortsRoute: AppSalesCohortsRoute,
  AppSalesManagerOfficeRoute: AppSalesManagerOfficeRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSmsAutomationRoute: AppSmsAutomationRoute,
  AppStaffRoute: AppStaffRoute,
  AppStaffEarningsRoute: AppStaffEarningsRoute,
  AppStaffPerformanceRoute: AppStaffPerformanceRoute,
  AppStateWhatsappGroupsRoute: AppStateWhatsappGroupsRoute,
  AppStockRecordRoute: AppStockRecordRoute,
  AppStorefrontRoute: AppStorefrontRoute,
  AppStorefrontCustomizationRoute: AppStorefrontCustomizationRoute,
  AppTrackingRoute: AppTrackingRoute,
  AppWalletRoute: AppWalletRoute,
  AppWaybillRoute: AppWaybillRoute,
  AppWhatsappAutomationRoute: AppWhatsappAutomationRoute,
  AppConnectionsAiProviderRoute: AppConnectionsAiProviderRoute,
  AppConnectionsElementorRoute: AppConnectionsElementorRoute,
  AppConnectionsEmailRoute: AppConnectionsEmailRoute,
  AppConnectionsPaymentGatewaysRoute: AppConnectionsPaymentGatewaysRoute,
  AppConnectionsSmsRoute: AppConnectionsSmsRoute,
  AppConnectionsWebhooksRoute: AppConnectionsWebhooksRoute,
  AppConnectionsWhatsappRoute: AppConnectionsWhatsappRoute,
  AppConnectionsWoocommerceRoute: AppConnectionsWoocommerceRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  FormSlugRoute: FormSlugRoute,
  SystemCreateOwnerRoute: SystemCreateOwnerRoute,
  TrackOrderCodeRoute: TrackOrderCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
